### ISSUE TITLE
Variable references are not parsed the same as less.js

### ISSUE THREAD

**Issue by tomprogramming** [dotless/dotless#364] opened 2014-05-02 18:35 UTC
For better or for worse less.js supports using a variable before it's been defined in the file.  This is done by several bootswatch developers, namely Flatly in their http://bootswatch.com/flatly/variables.less file.  (search for dropdown-link-active-bg, it's used on line 222 but defined on line 227, though there are other examples in there).

dotLess fails to parse these with a "Variable Undefined" error.

A simple test case would be:

```less
@var1 : @var2;

@var2: #ccc;

body { background: @var1; }
```

Less.js parses this just fine, but dotLess will not.

**Comment by rytmis** [comment] 2015-02-26 13:09
Duplicate of #312.

For a workaround, add the configuration parameter `disableVariableRedefines="true"` to your web.config or use the -v command line compiler switch.

Will have to discuss the issue, but I'm thinking 1.5 *might* be a good opportunity to change this behavior to match less.js.

**Closed by rytmis** 2015-02-26 13:09 UTC

**Comment by tomprogramming** [comment] 2015-02-26 13:20
I understand that this is probably going to be fixed by the same issue, but this isn't about redefining variables.  This is about using variables before they've been defined lexically.

**Comment by rytmis** [comment] 2015-02-26 13:35
You are right about the description, but the workaround still applies. 

The switch alternates between two modes of behavior: one where the redefinition is allowed and one where the variables are hoisted:

<pre>
PS C:\users\lauri\documents\github\dotless> .\build\dotless.Compiler.exe test.less
[Compile]
C:\users\lauri\documents\github\dotless\test.less -> C:\users\lauri\documents\github\dotless\test.css

variable @var2 is undefined on line 1 in file 'C:\users\lauri\documents\github\dotless\test.less':
   []: /beginning of file
  [1]: @var1 : @var2;
       --------^
  [2]:
[Done - Failed]
</pre>

vs:

<pre>
PS C:\users\lauri\documents\github\dotless> .\build\dotless.Compiler.exe -v test.less
[Compile]
C:\users\lauri\documents\github\dotless\test.less -> C:\users\lauri\documents\github\dotless\test.css
[Done]
</pre>
