### ISSUE TITLE
Is the IoC container thread safe?

### ISSUE THREAD

**Issue by yetanotherchris** [dotless/dotless#480] opened 2015-08-13 16:19 UTC
We're having a few problems currently with several large .less files being served up, and the `_j` property in `Tokenizor` outside the bounds of the `_chunks` array. 

The problem appears to be the Pandora IoC container's Transient implementation not being thread safe - the same `LessEngine` is being re-used.

The repo for this is putting 4-5 large less files on the *same* page (try importaing the Bootstrap frameowork LESS files) with the HttpHandler. One of the files throws a 500 error, but will be fine once the other files have been compiled.

I can try moving to Structuremap and sending a pull request (providing it works), however is this change likely to be accepted?

**Comment by rytmis** [comment] 2015-08-13 19:06
Oh boy, this should be fun.

I took a cursory look at the transient lifetime scope of Pandora, and on the surface it seems like it should be impossible for it to return the same instance for multiple callers. I would also expect to have encountered this already, having e.g. load tested sites with large LESS files in them. But concurrency is hard, so yeah... let's see if I can repro this. Can you make it reproduce with, say, a vanilla ASP.NET MVC 5 website that imports Bootstrap.less five or more times? That would be a great way to dig in to the issue.

I'm not opposed to getting rid of Pandora, particularly in the way it is used today -- internalized via ILMerge. However, I would like to first take a closer look at the issue and see if it can be fixed with a less intrusive change for now.

2.0 would be a great place to expose IoC in a way that would be consistent with e.g. the way people expect IoC to work in ASP.NET apps in general: by allowing people to bring their own container. Switching from one hard-wired container to another in a minor feature release seems a bit iffy in that regard.

However, if it turns out that Pandora can't be made to work, then sure, let's talk about an alternative container in the pre-2.0 timeline. :)

**Comment by rytmis** [comment] 2015-08-13 19:14
OTOH, 2.0 seems fairly distant right now given the amount of work needed. That lends some weight to the argument that we should do something in the shorter term. This might actually be a good opportunity to crack the IoC container open and solve issues like #463. :)

**Comment by yetanotherchris** [comment] 2015-08-13 21:10
It's a guess that the problem is the IoC, just from the arrays being out of bounds. What doesn't add up is that if I new up a LessEngine myself, in the factory, the problem still happens so maybe it's just somewhere else in the `Tokenizor`. This class does assume that `_j` is always as big as the `_chunk` array but I suppose it should always be.

I'll try to make an MVC app to reproduce it, we're using `@import (reference)` a lot.

**Comment by yetanotherchris** [comment] 2015-08-13 21:16
This may also be something to do with it, although we've only got about 5 LESS files so it would be weird if ASP.NET was reusing instances.

https://github.com/dotless/dotless/blob/master/src/dotless.AspNet/LessCssHttpHandler.cs#L50

**Comment by rytmis** [comment] 2015-08-14 04:10
It would still reduce back to Transient working incorrectly, because the handler has no shared state, though. If you can reproduce it by new'ing up an engine, do you still need five concurrent requests for it to happen?

**Comment by yetanotherchris** [comment] 2015-08-14 12:46
I've managed to reproduce it fairly easily, with quite an extreme example (10 bootstrap @import statements on 5 different less files).

Hopefully it will compile ok for you:

https://github.com/yetanotherchris/dotlessissue480

**Comment by rytmis** [comment] 2015-08-14 13:04
Out of curiosity, do the multiple repeated imports make a difference? Because they shouldn't -- repeated top-level imports of the same file should be de-duped. :)

**Comment by yetanotherchris** [comment] 2015-08-14 14:11
Yeh please ignore the multiple calls, they were just testing it out

**Comment by elacy** [comment] 2015-11-24 16:44
Hey! Any movement on this, running into this problem too

**Comment by elacy** [comment] 2015-11-24 17:27
The problem I'm getting seems to be caused by this line where the Parser is being stored statically 
https://github.com/dotless/dotless/blob/master/src/dotless.Core/Parser/Tree/Selector.cs#L28

**Comment by rytmis** [comment] 2015-11-24 18:28
Oops, I'm pretty sure that's my bad. I'll see if I can spare a bit of time to wrap up the fixes that have been waiting along with a fix for that tomorrow. 

Do you have a repro? I recall trying to repro it unsuccessfully, which is probably why it never got fixed. 

Awesome job tracking it down!

**Comment by elacy** [comment] 2015-11-24 18:40
If you add a LessTransform to your Bundle with a bootstrap.less in it, restart your app and send about 10 requests at it should do it

**Comment by rytmis** [comment] 2015-11-24 20:17
I seem to recall trying that the last time this came up, with little success. Will try again after work tomorrow, and even if I fail to repro it, we can proceed on the assumption that your diagnosis is correct, because it's fairly obvious now that you pointed it out.

**Comment by yetanotherchris** [comment] 2015-11-24 20:19
We had to abandon Dotless unfortunately, at least for the web application
that the trouble was coming from (about 5 .less files are downloaded
simultaneously). I would've liked to have looked into the problem but it
seemed to be quite involved and needed a lot of knowledge of the Dotless
source.

For now, we use Dotless for inlined SVG assets, and Grunt/Node for the rest
of the Less.

**Comment by rytmis** [comment] 2015-11-25 14:19
Yeah, now that @elacy pointed out the statics to me in this context, it's obvious that I've had a dumb when I wrote it. The parser is stateful, so of course it's not threadsafe -- but creating one for each Selector is far from ideal either. Actually, we really _should_ use the parser from the entry point, but that was far too involved a change to make, so I ended up making a really poor choice instead.

I've switched it to a lazily initialized ThreadStatic now. The change is available in 1.5.2-beta2 (up on nuget.org now). Can you please give it a try? I've tried reproducing the problem before and tried again now with no success (poor timing, I guess).

**Comment by rytmis** [comment] 2015-11-27 06:09
Ookay, I finally managed to reproduce the issue now, even with the ThreadStatic change. Will investigate.

**Comment by rytmis** [comment] 2015-11-27 06:17
Er... strike that, the error was just a bad config. So, to recap:

- I've now successfully reproduced the issue with 1.5.2-beta1 by linking to five different less files, all of which import Bootstrap. Four out of five fail consistently.
- Switching to 1.5.2-beta4, they all work
- Switching back and forth produces consistent results: beta1 fails, beta4 doesn't. 

I'm fairly confident that this fixes the issue, but please give it a try in the next few days if you can -- I want to push out 1.5.2 soon.

**Comment by rytmis** [comment] 2015-12-03 07:28
I'm going with the assumption that 1.5.2 fixes this. If that's not the case, then please reopen the issue.

**Closed by rytmis** 2015-12-03 07:28 UTC
