### ISSUE TITLE
Minification doesn't seems to work

### ISSUE THREAD

**Issue by julienfroidefond** [dotless/dotless#381] opened 2014-07-08 09:16 UTC
If I put minifyCss="true" in my web.config, I have this issue : 

.pull-right>.dropdown-menu is undefined on line 183 in file '../iso_icons/dropdowns.less':
[182]:     .dropdown-menu {
[183]:       .pull-right > .dropdown-menu();
       ------^
[184]:     }

I notice, it's a rule from bootstrap 3 in dropdown.less (v : 3.0.3)

But in not minified, this works well.

The version is the one I take is from the nuget package (1.4.0.0)
It's causing me perfs problems.
Thx

**Comment by rytmis** [comment] 2015-02-26 13:11
Duplicate of #346

**Closed by rytmis** 2015-02-26 13:11 UTC
