### ISSUE TITLE
Problem with @import statement

### ISSUE THREAD

**Issue by mckn** [dotless/dotless#352] opened 2014-01-14 16:54 UTC
I upgraded to dotless version 1.4.0 and got the following issue:

My file structure looks like this:

\styles\variables.less (130 lines of code, only variable declerations)
\styles\grid.less (30 lines of code, a simple grid made with mixins)
\styles\modules\module.less (ordinary less style file)

Module.less imports first the grid.less and second the variables.less. When I try to TransformToCss it gives me an empty string and a debug-text saying:

variable @bg-color is undefined on line 19 in file '~/styles/modules/module.less':
 [18]: 	padding: 20px;
 [19]: 	background: @bg-color;
       -------------^
 [20]: }
variable @bg-color is undefined on line 19 in file '~/styles/modules/module.less':
 [18]: 	padding: 20px;
 [19]: 	background: @bg-color;
       -------------^
 [20]: }
variable @bg-color is undefined on line 19 in file '~/styles/modules/module.less':
 [18]: 	padding: 20px;
 [19]: 	background: @bg-color;
       -------------^
 [20]: }

I have a asp.net application and using the built-in bundling with the following adapter:

https://github.com/scott-xu/System.Web.Optimization.Less

If I downgrade to dotless 1.3.1 everything works just fine..so it seems to be a problem with the dotless parser.

Hope you can help me with this issue, Thanks!

**Comment by rytmis** [comment] 2015-02-26 13:12
Dupe of #312, I think

**Closed by rytmis** 2015-02-26 13:12 UTC
