### ISSUE TITLE
Add support for merge operator

### ISSUE THREAD

**Issue by AjithR04** [dotless/dotless#505] opened 2016-04-29 04:55 UTC
I have referred this in the less document

http://lesscss.org/features/#merge-feature-space

I have tried to append the values using +_ in less, but it throws the error expected '}' but found '{'in dotless compiler. Is there anything I missed? How to append the values in dotLess compiler?

```
.gradient(@brow){      
    @{brow}+_: ~"; background: @{brow}linear-gradient(top";
     // some content
  }
}
```

Error indicates in this line @{brow}+_:

**Comment by rytmis** [comment] 2016-04-29 05:57
Unfortunately, we don't currently support the merge operator (as evidenced by #473) .

**Comment by AjithR04** [comment] 2016-04-29 12:20
Thanks for the update. When will we get the next release 1.6.0?

**Comment by rytmis** [comment] 2016-04-29 14:14
Ooh. Tough question, I've had practically zero time to dedicate to dotless since last August (case in point, dotless 1.5.3 is still not out) so we're a little short-staffed at the moment. :(

**Comment by rytmis** [comment] 2017-02-15 17:57
Duplicate of #473

**Closed by rytmis** 2017-02-15 17:57 UTC
