### ISSUE TITLE
Parse of '@import (less)' statement raises NullReferenceException

### ISSUE THREAD

**Issue by Deilan** [dotless/dotless#397] opened 2014-10-15 16:53 UTC
Visual Studio 2013.3 with Web Essentials, ASP .NET MVC 5 Project with dotLess 1.4.1. Attempt to use '@import (less)' statement inside of a simple less file, that only imports a simple css file, leads to a raise of NullReferenceException. '@import' without '(less)' instruction does not parsed as expected - it just being copied unparsed to the result less file. Is there a way to fix that?

Steps to reproduce:

1) Create a new ASP .NET MVC 5 Project in Visual Studio 2013.3
2) Install the latest version of dotless via NuGet Package Manager
3) Inside ~/Content/ folder create a simple Site.less file, that only imports the default Site.css files:
@import (less) "Site.css";

4) According to Bundling and Minification article of ASP .NET MVC 4 tutorial create LessTransform class as follows:

using System.Web.Optimization;

public class LessTransform : IBundleTransform
{
    public void Process(BundleContext context, BundleResponse response)
    {
        response.Content = dotless.Core.Less.Parse(response.Content);
        response.ContentType = "text/css";
    }
}

5) In RegisterBundles method inside of BundleConfig class in BundleConfig.cs file add the following lines:

var lessBundle = new Bundle("~/Content/less").Include("~/Content/Site.less");
lessBundle.Transforms.Add(new LessTransform());
bundles.Add(lessBundle);

6) In _Layout.cshtml file delete (or just comment out) the line:
@Styles.Render("~/Content/css")

and also add the following line:
@Styles.Render("~/Content/less")

7) Run the project

Result: NullReferenceException is thrown in LessTransform class on the line:
response.Content = Less.Parse(response.Content);

**Comment by kberridge** [comment] 2015-01-02 19:13
I too was just trying to use @import (less) or @import (inline) as described here http://lesscss.org/features/#import-options.  I did a quick read through the code and as far as I can tell it seems dotless does not support the "Import Options" feature?

**Comment by foxanthony** [comment] 2015-02-23 04:00
@import (inline), @import (css) leads to null pointer exception too for me.
There is the stack trace:
[FAILED]                                                                                                    
Compilation failed: Object reference not set to an instance of an object.                                   
   at dotless.Core.Parser.Parsers.Directive(Parser parser)                                                  
   at dotless.Core.Parser.Parsers.Primary(Parser parser)                                                    
   at dotless.Core.Parser.Parser.Parse(String input, String fileName)                                       
   at dotless.Core.LessEngine.TransformToCss(String source, String fileName)                                
   at dotless.Core.ParameterDecorator.TransformToCss(String source, String fileName)                        
   at dotless.Compiler.FixImportPathDecorator.TransformToCss(String source, String fileName)                
   at dotless.Compiler.Program.CompileImpl(ILessEngine engine, String inputFilePath, String outputFilePath) 

I'm using version 1.4.2.0 (nuget).

**Comment by rytmis** [comment] 2015-02-26 12:33
This is a duplicate of #378: @import options are not yet implemented. But they will be, once I get the bugfixes sorted out. In the meantime, 1.4.3 will recognize them and print a meaningful error.

**Closed by rytmis** 2015-02-26 12:33 UTC
