### ISSUE TITLE
Using @import and variables on multiple files

### ISSUE THREAD

**Issue by cgatian** [dotless/dotless#377] opened 2014-06-19 15:38 UTC
Take the following three .less files.

colors.less 
------------
@main-color:red;

styles.less
------------
@import "colors.less";
div
{
    color:@main-color;
}

customStyles.less
------------
@import "styles.less"
@main-color:green;

When you compile customStyles.less the div color should be green due to lazy loaded variables. But the variable value is red.  I tried using the 1.3.1 and 1.4 versions of dotLess.compiler.exe to execute the compilation and still see this issue.

**Comment by rytmis** [comment] 2015-02-26 13:10
Dupe of #312 like @euzureau pointed out. Will discuss changing the default behavior in the next feature release.

**Closed by rytmis** 2015-02-26 13:10 UTC
