### ISSUE TITLE
NullReferenceException & IndexOutOfRangeException in multithreading usage

### ISSUE THREAD

**Issue by SavchukSergey** [dotless/dotless#492] opened 2015-09-28 08:13 UTC
Sometimes I get either NullReferenceException or IndexOutOfRangeException when running dotless in multithreading environment. See stacktrace at the end of message
My code looks like:
```
dotless.Core.Less.Parse(less, _config);
```
When I wrap this line in lock section everything works stable. But this obviously causes performance degradation.

I think bug is in InMemoryCache implementation at least. This component is registered with default lifestyle. Which I guess is a singleton that makes sense for a cache.
InMemoryCache uses Dictionary without any synchronization. ConcurrentDictionary might be more appropriate for this case.

NullReferenceException:
```
   at dotless.Core.Parser.Tokenizer.SetupInput(String input, String fileName)
   at dotless.Core.Parser.Tree.Selector.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRules(Env env)
   at dotless.Core.Parser.Tree.Ruleset.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRules(Env env)
   at dotless.Core.Parser.Tree.Root.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Root.AppendCSS(Env env)
   at dotless.Core.Parser.Infrastructure.Output.Append(Node node)
   at dotless.Core.Parser.Infrastructure.Nodes.Node.ToCSS(Env env)
   at dotless.Core.LessEngine.TransformToCss(String source, String fileName)
   at dotless.Core.CacheDecorator.TransformToCss(String source, String fileName)
   at dotless.Core.ParameterDecorator.TransformToCss(String source, String fileName)
```

IndexOutOfRangeException:
```
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at dotless.Core.Parser.Tokenizer.Match(String tok, Boolean caseInsensitive)
   at dotless.Core.Parser.Parsers.NonPseudoClassSelector(Parser parser)
   at dotless.Core.Parser.Parsers.Element(Parser parser)
   at dotless.Core.Parser.Parsers.Selector(Parser parser)
   at dotless.Core.Parser.Tree.Selector.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRules(Env env)
   at dotless.Core.Parser.Tree.Ruleset.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRules(Env env)
   at dotless.Core.Parser.Tree.Root.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Root.AppendCSS(Env env)
   at dotless.Core.Parser.Infrastructure.Output.Append(Node node)
   at dotless.Core.Parser.Infrastructure.Nodes.Node.ToCSS(Env env)
   at dotless.Core.LessEngine.TransformToCss(String source, String fileName)
   at dotless.Core.CacheDecorator.TransformToCss(String source, String fileName)
   at dotless.Core.ParameterDecorator.TransformToCss(String source, String fileName)
```

**Comment by rytmis** [comment] 2015-11-25 14:59
This also sounds like a duplicate of #480 -- can you give 1.5.2-beta2 a try, it contains a candidate fix for the issue?

**Comment by rytmis** [comment] 2015-12-03 07:28
I'm going with the assumption that 1.5.2 fixes this. If that's not the case, then please reopen the issue.

**Closed by rytmis** 2015-12-03 07:28 UTC
