### ISSUE TITLE
Dotless error when query string is supplied

### ISSUE THREAD

**Issue by ampeixoto** [dotless/dotless#447] opened 2015-06-02 09:03 UTC
I'm having the issue explained here:

[.less compilation error when query string is supplied](http://stackoverflow.com/questions/27398806/less-compilation-error-when-query-string-is-supplied)

Also, the following is also happening (it is described in one of the comments of the question):

> If it is the first hit into the application after compilation or redeploy (so the application is JIT compiling) then the above occurs. This is when the .less is compiled. Subsequent calls to this endpoint after the JITing then no issues occur because the .less has been compiled.

What could be the problem? I'm available to help in the debugging process so if you have some question, you can ask.

**Comment by ampeixoto** [comment] 2015-06-02 09:24
I just solved the problem by updating `dotless` and `dotless adapterfor System.Web.Optimization` to their last available versions:

 - `dotless`: 1.5.0
 - `dotless adapterfor System.Web.Optimization`: 1.3.3

**Comment by rytmis** [comment] 2015-06-02 10:59
This is a duplicate of #418, fixed in release 1.4.3. :)

**Closed by rytmis** 2015-06-02 10:59 UTC
