### ISSUE TITLE
Compiler throws object reference error when compiling filter style

### ISSUE THREAD

**Issue by bmeyers43** [dotless/dotless#354] opened 2014-01-31 07:13 UTC
When I use dotless.compiler.exe (v1.4.0.0) to compile this:

```css
x {
    filter: alpha(opacity=70);
}
```

It works fine. 

If I try to compile this (note the space before the "="):

```css
x {
    filter: alpha(opacity =70);
}
```

I get the following error:

>Compilation failed: Object reference not set to an instance of an object.
>     at dotless.Core.Parser.Zone..ctor(NodeLocation location, String error, Zone callZone)
>     at dotless.Core.Parser.Parser.GenerateParserError(ParsingException parsingException)
>     at dotless.Core.Parser.Parser.<Parse>b__2(ParsingException e)
>     at dotless.Core.Parser.Tree.Root.Evaluate(Env env)
>     at dotless.Core.Parser.Tree.Ruleset.AppendCSS(Env env)
>     at dotless.Core.Parser.Tree.Root.AppendCSS(Env env)
>     at dotless.Core.Parser.Infrastructure.Output.Append(Node node)
>     at dotless.Core.Parser.Infrastructure.Nodes.Node.ToCSS(Env env)
>     at dotless.Core.LessEngine.TransformToCss(String source, String fileName)
>     at dotless.Core.ParameterDecorator.TransformToCss(String source, String fileName)
>     at dotless.Compiler.FixImportPathDecorator.TransformToCss(String source, String fileName)
>     at dotless.Compiler.Program.CompileImpl(ILessEngine engine, String inputFilePath, String outputFilePath)

Please fix.

**Comment by rytmis** [comment] 2015-02-25 17:59
Duplicate of #288, I think.

**Closed** 2015-02-26 12:17 UTC
