### ISSUE TITLE
Compiler fails on bootstrap-3.1.0

### ISSUE THREAD

**Issue by NikGovorov** [dotless/dotless#356] opened 2014-02-01 12:34 UTC
Error message: 

```
Expected '}' but found ':' on line 648 in file 'libs/bootstrap-3.1.0/mixins.less':
[647]:   padding-right: (@grid-gutter-width / 2);
[648]:   &:extend(.clearfix all);
      --^
[649]: }

```

**Comment by rytmis** [comment] 2015-02-25 16:24
Closing as a duplicate of #355. There are some bugs regarding :extend in the currently shipping version, but they should be fixed in the upcoming 1.4.3 release.

**Closed by rytmis** 2015-02-25 16:24 UTC
