### ISSUE TITLE
v1.3.1.0 Doesn't Work in Medium Trust

### ISSUE THREAD

**Issue by jmotes** [dotless/dotless#308] opened 2013-06-17 16:21 UTC
I tried using dotnetless on Rackspace Cloud Sites, but got error 500 when loading the .less file. This is with .NET4 - 4.5 (tried both) and MVC 4.

I can reproduce the issue locally by setting trust level="Medium" in my Web.config file and then loading the .less file in a browser. Here is the top portion of the stack trace:

[SecurityException: Request for the permission of type 'System.Configuration.ConfigurationPermission, System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' failed.]

**Comment by rytmis** [comment] 2015-02-25 18:11
Dupe of #228.

**Closed by rytmis** 2015-02-25 18:11 UTC
