### ISSUE TITLE
Mixins as params not working

### ISSUE THREAD

**Issue by dsvictorh** [dotless/dotless#516] opened 2016-10-27 17:28 UTC
When using parametric mixins you can pass an anonymous mixin and call it as function with no params:

```
.media-tablet(@styles) {
    @media screen and (max-width: 1024px), screen and (max-device-width: 1024px) {
              @styles();
    }
}
```

The media-tablet mixin then can then be used like this:

```
.some-div{
    padding: 10px;
    margin: 0;

    .media-tablet({
      padding: 0;
      margin: 10px;
    });
}

```

Unfortunately dotless doesn't like it that you do not use property : value declaration and counts it as an error. I have tested this with other LESS processors like crunch and it has always worked.

**Comment by rytmis** [comment] 2016-10-31 07:34
Duplicate of #459

**Comment by Tigraine** [comment] 2016-10-31 09:18
Closing this for now as it's a duplicate - but we should get this feature done at some point..

**Closed** 2016-10-31 09:17 UTC
