### ISSUE TITLE
Using `&.class` renders an unintended space between the element and the class

### ISSUE THREAD

**Issue by drinkbird** [dotless/dotless#475] opened 2015-08-04 11:02 UTC
I noticed this issue while trying to compile Bootstrap 3.3.5 LESS sources

The mixin
```less
  .table > thead > tr,
  .table > tbody > tr,
  .table > tfoot > tr {
    > td.@{state},
    > th.@{state},
    &.@{state} > td,
    &.@{state} > th {
      background-color: @background;
    }
  }
```
renders to 
```css
.table > thead > tr > td.active,
.table > tbody > tr > td.active,
.table > tfoot > tr > td.active,
.table > thead > tr > th.active,
.table > tbody > tr > th.active,
.table > tfoot > tr > th.active,
.table > thead > tr .active > td,
.table > tbody > tr .active > td,
.table > tfoot > tr .active > td,
.table > thead > tr .active > th,
.table > tbody > tr .active > th,
.table > tfoot > tr .active > th {
  background-color: whitesmoke;
}
```

The problem is that eg `.table > thead > tr .active > td` should be rendered as `.table > thead > tr.active > td`

I'm using dotless v1.5.0

**Comment by rytmis** [comment] 2015-08-04 11:07
This might be a duplicate of #466 -- can you please try with 1.5.1 and see if it still reproduces?

**Comment by drinkbird** [comment] 2015-08-04 11:32
It's a duplicate indeed, sorry for that. Works like a charm.

**Comment by rytmis** [comment] 2015-08-04 11:36
Thanks for confirming!

**Closed by rytmis** 2015-08-04 11:36 UTC
