### ISSUE TITLE
I'm using Kendo less files and dotless fails on following declaration:

### ISSUE THREAD

**Issue by msmolka** [dotless/dotless#422] opened 2015-02-18 10:20 UTC
dotless fails on following declaration:

<code>
.sprite-hoverable-rtl(@row, @column, @size: @grid-size) when (ispixel(@column)) {

    .k-rtl & {
        .sprite-position(@row, @column);
    }

    .k-rtl .k-link:not(.k-state-disabled):hover > &,
    .k-rtl .k-state-hover > &,
    .k-rtl .k-state-hover > * > &,
    .k-rtl .k-button:not(.k-state-disabled):hover &,
    .k-rtl .k-textbox:hover &,
    .k-rtl .k-button:active & {
        .sprite-position(@row - @size, @column);

        & when (@icon-positioning = "material") {
            .sprite-position(@row, @column);
        }
    }
}
</code>

<code>
& when (@icon-positioning = "material") {
        .sprite-position(@row, @column);
    }
</code>

**Comment by rytmis** [comment] 2015-02-19 08:08
Can you whip up a minimal example that exhibits the problem? I didn't find the Kendo UI LESS files at the Telerik site.

**Comment by msmolka** [comment] 2015-02-19 08:19
Hello
Here is attached example of problematic part:
I cannot attach less file, so I've changed extension to png.
Download the file and rename to test.less.
![test](https://cloud.githubusercontent.com/assets/6661461/6263457/5bc4ac5e-b818-11e4-8d25-9dcae09f26e4.png)

Kind Regards
Marcin

**Comment by rytmis** [comment] 2015-02-19 19:44
Thanks. I'm working on a couple of other things in dotless right now, but I'll take a look at it as soon as I have the time. Note that the best I can do is a PR, though, as I'm not part of the dotless team. :-)

**Comment by rytmis** [comment] 2015-02-27 08:41
Ah, I see: this is actually a duplicate of #404. There's an open pull request on this -- I'll take a look at integrating it for the next feature release once I get a bugfix release out.

**Closed by rytmis** 2015-02-27 08:41 UTC

**Comment by rytmis** [comment] 2015-03-21 10:31
There's a prerelease of 1.5 available that compiles the Kendo UI files. I don't know if the result is 100% correct, but at least the compiler doesn't fail on anything as far as I can tell.

You can get it at https://www.nuget.org/packages/dotless/1.5.0-alpha1  (or Install-Package dotless -Pre in the package manager console)
